WEB/WEB/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^iotSystem/',include("iotSystem.urls",namespace='iotSystem')),
    url(r'^users/',include('users.urls',namespace="users")),
]

WEB/iotSystem/urls.py
#coding:utf-8
from django.conf.urls import url,include
from . import views
urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^data_dis/$', views.data_dis, name='data_dis'),
    #url(r'^state_in/$',views.state_in,name="state_in"),
    url(r'^data_history/$',views.data_history,name="data_history"),
    url(r"data_in/$",views.data_in,name="data_in"),
    url(r"ajax_data/$", views.ajax_data, name="ajax_data"),
   #url(r"^dataShow/$",views.dataShow,name="dataShow"),
    url(r"^position/$", views.position, name="position"),
    url(r"^historyDataFilter/$", views.historyDataFilter, name="historyDataFilter"),
    url(r"^introduce/$", views.introduce, name="introduce"),
    url(r"^background/$", views.background, name="background"),
    url(r"^warningHistory/$", views.warningHistory, name="warningHistory"),
    url(r"^control/$", views.control, name="control"),
]

WEB/users/urls.py
#coding:utf-8
from django.conf.urls import url,include
from . import views
from users.views import LoginView,LogoutView
urlpatterns = [
    url(r'^$',LoginView.as_view(),name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

WEB/templates/control.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>设备控制</title>
	<link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrapSwitch.css?v=3.3.6" rel="stylesheet">
    <!-- 引入 echarts.js -->
	 <script src="/statics/js/jquery.min.js?v=2.1.4"></script>
    <script src="/statics/js/bootstrapSwitch.js"></script>
</head>
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
	<div class="container">
		<ul class="list-group">
			<li class="list-group-item">欢迎进入物联网实时监控系统</li>
		</ul>
		<div class="row" >

			<div class="col-md-12" style="border-left:red 2px solid;height:400px;">
				<ul class="list-group">
					<li class="list-group-item">设备控制</li>
				</ul>

                <div>
                    <h2>控制设备开关</h2>
                        <div class="switch" id="myswitch1" style="margin-right:100px;">
                                  <input type="checkbox"  />
                         </div>
                    </div>
			</div>
		</div>


	</div>
    <script type="text/javascript">



    	 function sendToServer(url)
        {
			console.log(url);
             $.ajax({
                  async:true,
                    url:url,
                    type:"GET",
					success:function(data){
						console.log("success!");
					},
               });

        }
		var ledUrl="http://120.76.28.207:5005/?id=17864228068&command=transmitOther&data=";
	$("#myswitch1").on("switch-change",function(e,data){
      var value=data.value;
        if(value)
        {
         //   switch1="1"
		    sendToServer(ledUrl+"1");
        }
        else
        {

            sendToServer(ledUrl+"0");
        }

    });


 </script>






















</body>
</html>

WEB/templates/historyDataFilter.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>历史数据曲线</title>
	<link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrapSwitch.css?v=3.3.6" rel="stylesheet">
    <!-- 引入 echarts.js -->
	 <script src="/statics/js/jquery.min.js?v=2.1.4"></script>
    <script src="https://cdn.bootcss.com/echarts/4.1.0.rc2/echarts-en.min.js"></script>
    <script src="/statics/js/bootstrapSwitch.js"></script>
    <link href="/statics/css/font-awesome.css?v=4.4.0" rel="stylesheet">
    <link href="/statics/css/animate.css" rel="stylesheet">
    <link href="/statics/css/style.css?v=4.1.0" rel="stylesheet">
    <script src="/statics/js/loading.js"></script>
</head>
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
	<div class="container">
        <div class="col-sm-12" style="margin-top:20px;">
                <form class="form-inline pull-left" role="form" method="post" action="{% url 'iotSystem:historyDataFilter' %}">
                     {% csrf_token %}
                    <div class="form-group">
                        <select name="time"class="form-control">
                            <option value="0">三十分钟</option>
                            <option value="1">一个小时</option>
                            <option value="2">六个小时</option>
                            <option value="3">十二小时</option>
                            </select>
                        </div>
                    <div class="form-group">
                        <input id="start" name="start" class="form-control layer-date" placeholder="开始日期">&nbsp;&nbsp;<lable style="font-weight:bold;">到</lable>&nbsp;&nbsp;
                        <input id="end" name="end" class="form-control layer-date" placeholder="结束日期">
                        </div>
                    <button type="submit" class="btn btn-info">检索</button>
                    </form>
        </div>
                <div class="row" style="margin-top:100px;">
                    <div class="col-md-12" id="main" style="height:400px;">
                    </div>
                 </div>

	    </div>
    </div>
    <!-- layerDate plugin javascript -->
    <script src="/statics/js/plugins/layer/laydate/laydate.js"></script>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
	$(function() {

        var myChart = echarts.init(document.getElementById('main'));
        //日期范围限制
        var start = {
            elem: '#start',
            format: 'YYYY/MM/DD hh:mm:ss',
           // min: laydate.now(), //设定最小日期为当前日期
            max: '2099-06-16 23:59:59', //最大日期
            istime: true,
            istoday: false,
            choose: function (datas) {
                end.min = datas; //开始日选好后，重置结束日的最小日期
                end.start = datas ;//将结束日的初始值设定为开始日
            }
        };
        var end = {
            elem: '#end',
            format: 'YYYY/MM/DD hh:mm:ss',
          //  min: laydate.now(),
            max: '2099-06-16 23:59:59',
            istime: true,
            istoday: false,
            choose: function (datas) {
               start.max = datas; //结束日选好后，重置开始日的最大日期
            }
        };
        laydate(start);
        laydate(end);



        //曲线
                    var humiData = [],tempData=[],pmData=[];
            var data={{ data_list|safe }};
            for(var i=0;i<data.length;i++)
            {
                humiData.push({
                    name:data[i].time,
                    value:[data[i].time,data[i].humi]
                });
                  tempData.push({
                    name:data[i].time,
                    value:[data[i].time,data[i].temp]
                });
                  pmData.push({
                    name:data[i].time,
                    value:[data[i].time,data[i].pm]
                });
            }
option = {
    title: {
        text: '历史数据曲线分析'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['温度','湿度','PM2.5']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
       type:'time'
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'温度',
            type:'line',

            data:tempData
        },
        {
            name:'湿度',
            type:'line',

            data:humiData
        },
        {
            name:'PM2.5',
            type:'line',

            data:pmData
        }
    ]
};
        myChart.setOption(option);
    });

 </script>






















</body>
</html>

WEB/templates/index.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">

    <title>IO+物联网系统</title>

    <meta name="keywords" content="IO+物联网系统">
    <meta name="description" content="IO+物联网系统">

    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->

    <link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/statics/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/statics/css/animate.css" rel="stylesheet">
    <link href="/statics/css/style.css?v=4.1.0" rel="stylesheet">
</head>

<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">

    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close"><i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                          <!--  <span><img alt="image" class="img-circle" src="img/profile_small.jpg" /></span> !-->
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                               <span class="block m-t-xs"><strong class="font-bold">{{ request.user.username }}</strong></span>
                                <span class="text-muted text-xs block">管理员<b class="caret"></b></span>
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="J_menuItem" href="form_avatar.html">修改头像</a>
                                </li>
                                <li><a class="J_menuItem" href="profile.html">个人资料</a>
                                </li>
                                <li><a class="J_menuItem" href="contacts.html">联系我们</a>
                                </li>
                                <li><a class="J_menuItem" href="mailbox.html">信箱</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="{%  url 'users:logout' %}">安全退出</a>
                                </li>
                            </ul>
                        </div>
                        <div class="logo-element">IOT
                        </div>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">项目介绍</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                             <li>
                                <a class="J_menuItem" href="{%  url 'iotSystem:introduce' %}" data-index="0">时间线</a>
                            </li>

                        </ul>

                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-tint"></i>
                            <span class="nav-label">数据信息</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="{%  url 'iotSystem:data_dis' %}" data-index="0">实时数据</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{%  url 'iotSystem:data_history' %}">历史数据</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{%  url 'iotSystem:historyDataFilter' %}">历史数据分析</a>
                            </li>
                        </ul>

                    </li>

                    <li>
                        <a href="#">
                            <i class="fa fa-bell"></i>
                            <span class="nav-label">报警状态</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                             <li>
                                <a class="J_menuItem" href="{%  url 'iotSystem:warningHistory' %}">报警历史</a>
                            </li>

                        </ul>

                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-map-marker"></i>
                            <span class="nav-label">传感器位置</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                             <li>
                                <a class="J_menuItem" href="{%  url 'iotSystem:position' %}">当前位置</a>
                            </li>

                        </ul>

                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-wrench"></i>
                            <span class="nav-label">设备控制</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                             <li>
                                <a class="J_menuItem" href="{%  url 'iotSystem:control' %}">设备控制</a>
                            </li>

                        </ul>

                    </li>
                    <!--
                    <li>
                        <a class="J_menuItem" href="layouts.html"><i class="fa fa-columns"></i> <span class="nav-label">设备监控</span></a>
                    </li>
         
                    !-->

                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header"><a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" method="post" action="search_results.html">
                            <div class="form-group">
                                <input type="text" placeholder="请输入您需要查找的内容 …" class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right" >
                        <li style="margin-top:20px;">IO+物联系统
						</li>
                    </ul>
                </nav>
            </div>
            <div class="row content-tabs">
                <button class="roll-nav roll-left J_tabLeft"><i class="fa fa-backward"></i>
                </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <a href="javascript:;" class="active J_menuTab" data-id="{% url 'iotSystem:data_dis' %}">首页</a>
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight"><i class="fa fa-forward"></i>
                </button>
                <div class="btn-group roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">关闭操作<span class="caret"></span>

                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive"><a>定位当前选项卡</a>
                        </li>
                        <li class="divider"></li>
                        <li class="J_tabCloseAll"><a>关闭全部选项卡</a>
                        </li>
                        <li class="J_tabCloseOther"><a>关闭其他选项卡</a>
                        </li>
                    </ul>
                </div>
                <a href="{%  url 'users:logout' %}" class="roll-nav roll-right J_tabExit"><i class="fa fa fa-sign-out"></i> 退出</a>
            </div>
            <div class="row J_mainContent" id="content-main">
                <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="{% url 'iotSystem:data_dis' %}" frameborder="0" data-id="{% url 'iotSystem:data_dis' %}" seamless></iframe>
            </div>
            <div class="footer">
                <div class="pull-right">&copy; 2018-2020 <a href="" target="_blank">IO+物联网系统</a>
                </div>
            </div>
        </div>
        <!--右侧部分结束-->

    </div>

    <!-- 全局js -->
    <script src="/statics/js/jquery.min.js?v=2.1.4"></script>
    <script src="/statics/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="/statics/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/statics/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/statics/js/plugins/layer/layer.min.js"></script>

    <!-- 自定义js -->
    <script src="/statics/js/hplus.js?v=4.1.0"></script>
    <script type="text/javascript" src="/statics/js/contabs.js"></script>

    <!-- 第三方插件 -->
    <script src="/statics/js/plugins/pace/pace.min.js"></script>

</body>

</html>

WEB/templates/index_v1.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>实时数据</title>
     <script src="/statics/js/loading.js"></script>
	<link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrapSwitch.css?v=3.3.6" rel="stylesheet">
    <!-- 引入 echarts.js -->
	 <script src="/statics/js/jquery.min.js?v=2.1.4"></script>
    <script src="https://cdn.bootcss.com/echarts/4.1.0.rc2/echarts-en.min.js"></script>
    <script src="/statics/js/bootstrapSwitch.js"></script>

</head>
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
	<div class="container">
		<ul class="list-group">
			<li class="list-group-item">欢迎进入物联网实时监控系统</li>
		</ul>
		<div class="row" >
			<div class="col-md-6" id="main" style="height:400px;">
			</div>
			<div class="col-md-6" style="border-left:red 2px solid;height:400px;">
				<ul class="list-group">
					<li class="list-group-item">气体实时数据</li>
				</ul>
				
				<form role="form">
				  <div class="form-group">
					<label for="name">温度</label>
					<input type="text" class="form-control"name="temp" disabled="disabled">
					<label for="name">湿度</label>
					<!--<input type="text" class="form-control" name="humi" disabled="disabled">
                      <label for="name">光照</label>
                      !-->
					<input type="text" class="form-control" name="humi" disabled="disabled">
                      <label for="name">PM2.5粉尘</label>
					<input type="text" class="form-control" name="pm" disabled="disabled">
				  </div>
				 </form>

                <!--  实时控制家用电气!-->
{#？#}
{#                            <div class="switch" id="myswitch2">#}
{#                                 <input type="checkbox"  />#}
{#                            </div>#}
                    </div>
			</div>
		</div>
		
	
	</div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
	$(function()
	{
		
			var myChart = echarts.init(document.getElementById('main'));
            var humiData = [],tempData=[],pmData=[];
            var data={{ data_list|safe }};
            for(var i=0;i<data.length;i++)
            {
                humiData.push({
                    name:data[i].time,
                    value:[data[i].time,data[i].humi]
                });
                  tempData.push({
                    name:data[i].time,
                    value:[data[i].time,data[i].temp]
                });
                  pmData.push({
                    name:data[i].time,
                    value:[data[i].time,data[i].pm]
                });
            }
option = {
    title: {
        text: '实时数据'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['温度','湿度','pm']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
       type:'time'
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'温度',
            type:'line',

            data:tempData
        },
        {
            name:'湿度',
            type:'line',

            data:humiData
        },
        {
            name:'pm',
            type:'line',

            data:pmData
        }
    ]
};
//第一次初始化用
myChart.setOption(option);
var timeFlag="";
                //ajax
        setInterval(function () {
                        //ajax请求数据
                    $.ajax({
                            cache:false,
                            type:"POST",
                            url:"{% url 'iotSystem:ajax_data' %}",
                            async:true,
                            beforeSend:function(xhr, settings){
                                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                                },
                            success:function(data){
                                if(timeFlag==data.time) return;
                                timeFlag=data.time;
                                $("input[name='temp']").val(data.temp);
                                $("input[name='humi']").val(data.humi+"%");
                                $("input[name='pm']").val(data.pm);
                                     humiData.shift();
                                    humiData.push({
                                    name:data.time,
                                    value:[data.time,data.humi]
                                });
                                    tempData.shift();
                                    tempData.push({
                                    name:data.time,
                                    value:[data.time,data.temp]
                                });
                                pmData.shift();
                                    pmData.push({
                                    name:data.time,
                                    value:[data.time,data.pm]
                                });
                                             myChart.setOption({
                                                        series: [
                                                                    {
                                                                        name:'温度',
                                                                        type:'line',

                                                                        data:tempData
                                                                    },
                                                                    {
                                                                        name:'湿度',
                                                                        type:'line',

                                                                        data:humiData
                                                                    },
                                                                    {
                                                                        name:'pm',
                                                                        type:'line',

                                                                        data:pmData
                                                                    }
                                                                ]
                                                });

                            }
                        });

}, 2000);
        //first request
                    $.ajax({
                            cache:false,
                            type:"POST",
                            url:"{% url 'iotSystem:ajax_data' %}",
                            async:true,
                            beforeSend:function(xhr, settings){
                                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                                },
                            success:function(data){
                                if(timeFlag==data.time) return;
                                timeFlag=data.time;
                                $("input[name='temp']").val(data.temp);
                                $("input[name='humi']").val(data.humi+"%");
                                $("input[name='pm']").val(data.pm);
                                     humiData.unshift();
                                    humiData.push({
                                    name:data.time,
                                    value:[data.time,data.humi]
                                });
                                    tempData.unshift();
                                    tempData.push({
                                    name:data.time,
                                    value:[data.time,data.temp]
                                });
                                pmData.unshift();
                                    pmData.push({
                                    name:data.time,
                                    value:[data.time,data.pm]
                                });
                                             myChart.setOption({
                                                        series: [
                                                                    {
                                                                        name:'温度',
                                                                        type:'line',

                                                                        data:tempData
                                                                    },
                                                                    {
                                                                        name:'湿度',
                                                                        type:'line',

                                                                        data:humiData
                                                                    },
                                                                    {
                                                                        name:'pm',
                                                                        type:'line',

                                                                        data:pmData
                                                                    }
                                                                ]
                                                });

                            }
                        });
    });

 </script>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
</body>
</html>

WEB/templates/index_v2.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>历史数据</title>
     <script src="/statics/js/loading.js"></script>
	<link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <!-- 引入 echarts.js -->
	 <script src="/statics/js/jquery.min.js?v=2.1.4"></script>
    <script src="/statics/js/plugins/echarts/echarts.js"></script>
</head>
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
	
	
	<div class="container">
		<ul class="list-group">
			<li class="list-group-item">欢迎进入物联网实时监控系统</li>
		</ul>
		<div class="row" >

			<div class="col-md-12" style="border-left:red 2px solid;">
				<table class="table table-striped">
					  <caption>气体历史情况</caption>
					  <thead>
						<tr>
                            <th>温度</th>
                            <th>湿度</th>
						<!--  <th>光照</th> !-->
                            <th>PM2.5</th>
                            <th>经度</th>
                            <th>纬度</th>
						  <th>时间</th>
						</tr>
					  </thead>
					  <tbody>
                      {% for  dataone in data.object_list %}
{#                          <tr class="{% if dataone.flag %}danger{% endif %}">#}
                          <tr>
                        <td>{{ dataone.temp }}</td>
						  <td>{{ dataone.humi }}</td>
						  <td>{{ dataone.pm }}</td>
                          <td>{{ dataone.jingdu }}</td>
                              <td>{{ dataone.weidu }}</td>
                          <td>{{ dataone.time }}</td>
                          </tr>
{#						</tr>#}
                      {% endfor %}
					  </tbody>
					</table>

			</div>

</div>
{# The following renders the pagination html #}
<div id="pagination" style="margin-top:-40px;">
    {{ data.render }}
</div>


		
	
	</div>
    <script type="text/javascript">

		
		
 </script>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
</body>
</html>

WEB/templates/login.html
<!DOCTYPE html>
<html>
{% load static %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>物联网系统-登陆</title>
    <meta name="keywords" content="为物联网而生">
    <meta name="description" content="">

    <link rel="shortcut icon" href="favicon.ico"> <link href="/statics/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/statics/css/font-awesome.css?v=4.4.0" rel="stylesheet">

    <link href="/statics/css/animate.css" rel="stylesheet">
    <link href="/statics/css/style.css?v=4.1.0" rel="stylesheet">
    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->
    <script>if(window.top !== window.self){ window.top.location = window.location;}</script>
</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">IO+</h1>

            </div>
            <h3>欢迎登入我的物联网系统</h3>

            <form class="m-t" role="form" action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="用户名" required="" name="username">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="密码" required="" name="password">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">登 录</button>
                <p class="text-muted">{{ msg }}</p>

              <!--  <p class="text-muted text-center"> <a href="login.html#"><small>忘记密码了？</small></a> | <a href="register.html">注册一个新账号</a>
                </p>
                !-->
            </form>
        </div>
    </div>

    <!-- 全局js -->
    <script src="/statics/js/jquery.min.js?v=2.1.4"></script>
    <script src="/statics/js/bootstrap.min.js?v=3.3.6"></script>


    <!--统计代码，可删除-->

</body>

</html>